### ISSUE TITLE
Red color in csharp

### ISSUE THREAD

**Issue by martinib77** [andreluis-oliveira/vscode-palenight-theme-high-contrast#2]
Very nice color combination.
But for the csharp files, i found they use a lot of the red color, which looks like an error on the source.

Is it possible to replace the use of red?.

![colores-tema](https://github.com/andreluis-oliveira/vscode-luminescence-theme/assets/5649614/d824d6d9-cf7f-41eb-a631-62b482ed26a7)

**Comment by andreluis-oliveira** [comment]
Thanks for pointing this out

**Comment by andreluis-oliveira** [comment]
#3
